import type { OfflineResourcePack } from "@/lib/types";

export const offlineResourcePacks: OfflineResourcePack[] = [
  {
    id: "orp-react-core",
    title: "React Core Mental Models",
    slug: "react-core-mental-models",
    group: "react",
    mappedTracks: ["react"],
    category: "Official React mental models",
    summary: "A local digest of the React ideas that most often decide whether your answer sounds modern or outdated.",
    simpleStart: [
      "React first makes a fresh plan for what the screen should look like.",
      "Then it changes only the parts that really changed instead of rebuilding everything.",
      "Keys are like name tags that help React remember the right list item.",
    ],
    bestFor: "Rendering, state updates, re-renders, and explaining React without vague virtual-DOM-only answers.",
    whyThisMattersForYou:
      "Your resume already shows reusable components and performance work, so interviewers will expect clean React mental models, not only syntax.",
    keyTakeaways: [
      "Rendering is React calculating the next UI tree, not automatically a full DOM rewrite.",
      "State behaves like a snapshot for a specific render, which explains stale values and batched updates.",
      "The render phase and commit phase are different; React can render work without committing visible DOM changes.",
      "Keys preserve identity in lists and prevent broken state reuse.",
    ],
    interviewAngles: [
      "Explain render vs commit vs reconciliation in one clean answer.",
      "Use state-as-a-snapshot language when discussing stale closures or repeated setState calls.",
      "Connect these ideas to performance rather than treating them as theory-only concepts.",
    ],
    quickRevision: [
      "Render calculates.",
      "Commit shows changes.",
      "State is per-render snapshot.",
      "Keys preserve identity.",
    ],
    sourceRefs: [
      { title: "React Learn", url: "https://react.dev/learn", type: "official-docs" },
      { title: "Render and Commit", url: "https://react.dev/learn/render-and-commit", type: "official-docs" },
      { title: "State as a Snapshot", url: "https://react.dev/learn/state-as-a-snapshot", type: "official-docs" },
    ],
  },
  {
    id: "orp-react-effects",
    title: "React Effects and Data Flow",
    slug: "react-effects-and-data-flow",
    group: "react",
    mappedTracks: ["react", "system-design"],
    category: "Official React effects and state flow",
    summary: "A local study pack for useEffect, shared state, and the difference between side effects and derived data.",
    simpleStart: [
      "useEffect is for work that happens after the screen is shown.",
      "If you can calculate a value directly, do it in render instead of storing extra state.",
      "Shared state should live with the closest parent that truly needs it.",
    ],
    bestFor: "Modern React interview rounds that test whether you overuse effects or design state carefully.",
    whyThisMattersForYou:
      "Your profile already shows custom hooks and reusable component work, so stronger effect reasoning will make your answers feel senior within mid-level interviews.",
    keyTakeaways: [
      "useEffect is for syncing with external systems, not for every value transformation.",
      "If a value can be derived during render, storing it in state plus syncing it with an effect is often unnecessary.",
      "Shared state should move to the closest common owner, not jump to global state by default.",
      "Choosing state structure early prevents duplicated truth and hard-to-debug updates later.",
    ],
    interviewAngles: [
      "Answer 'When not to use useEffect?' with confidence.",
      "Use this pack when discussing lifted state, stale closures, and reducer-style workflow logic.",
      "Connect effect cleanup to real bugs: timers, subscriptions, and aborted requests.",
    ],
    quickRevision: [
      "Effect for external sync.",
      "Derived values stay in render.",
      "Lift state only when sharing is real.",
      "Bad state shape creates bad architecture.",
    ],
    sourceRefs: [
      { title: "Synchronizing with Effects", url: "https://react.dev/learn/synchronizing-with-effects", type: "official-docs" },
      { title: "You Might Not Need an Effect", url: "https://react.dev/learn/you-might-not-need-an-effect", type: "official-docs" },
      { title: "Sharing State Between Components", url: "https://react.dev/learn/sharing-state-between-components", type: "official-docs" },
      { title: "Choosing the State Structure", url: "https://react.dev/learn/choosing-the-state-structure", type: "official-docs" },
    ],
  },
  {
    id: "orp-js-runtime",
    title: "JavaScript Runtime and Closures",
    slug: "javascript-runtime-and-closures",
    group: "javascript",
    mappedTracks: ["javascript", "browser"],
    category: "Runtime, closures, and async behavior",
    summary: "A local offline guide to the JavaScript runtime ideas interviewers repeatedly use for JS and browser rounds.",
    simpleStart: [
      "A function remembers the variables around it from where it was created.",
      "JavaScript finishes the current work first before checking queued async work.",
      "Promise callbacks usually run before timer callbacks after the current code finishes.",
    ],
    bestFor: "Closures, lexical scope, event loop, microtasks, timers, promise ordering, and DOM callback behavior.",
    whyThisMattersForYou:
      "Since you already have solid React experience, interviewers will likely test whether your JavaScript depth matches your React confidence.",
    keyTakeaways: [
      "Closures remember the lexical scope where a function was created, not where it was called.",
      "The event loop runs microtasks before the next macrotask after the current stack clears.",
      "Promise callbacks and timer callbacks differ in scheduling, which explains common interview output questions.",
      "Main-thread blocking affects not only code order but also responsiveness and rendering.",
    ],
    interviewAngles: [
      "Use the closure explanation when discussing custom hooks, event handlers, and stale state.",
      "Use microtask vs macrotask language in async output questions.",
      "Connect runtime behavior to browser performance, not only to console.log examples.",
    ],
    quickRevision: [
      "Closure remembers definition scope.",
      "Stack first, microtasks second, next task after.",
      "Promises are microtasks.",
      "Busy JS blocks rendering too.",
    ],
    sourceRefs: [
      { title: "MDN Closures Guide", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Closures", type: "official-guide" },
      { title: "MDN JavaScript Execution Model", url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Event_loop", type: "official-guide" },
      { title: "javascript.info Event Loop", url: "https://javascript.info/event-loop", type: "official-guide" },
    ],
  },
  {
    id: "orp-typescript-react",
    title: "TypeScript for React Interviews",
    slug: "typescript-for-react-interviews",
    group: "frontend",
    mappedTracks: ["frontend", "react", "javascript"],
    category: "TypeScript for frontend interviews",
    summary: "A local TypeScript interview pack focused on the pieces that improve React answers instead of random language trivia.",
    simpleStart: [
      "TypeScript is like adding labels to your data so mistakes are caught early.",
      "Unions help you describe real UI states like loading, success, or error.",
      "Generics help one reusable function or hook work safely with many data shapes.",
    ],
    bestFor: "Props typing, unions, narrowing, generics, API models, and writing safer component contracts.",
    whyThisMattersForYou:
      "Your resume already lists TypeScript, so many companies will expect you to explain why it helps component design and team velocity.",
    keyTakeaways: [
      "Use unions to model real UI states like loading, success, and error more safely.",
      "Narrowing is critical when working with API data, optional values, and DOM event targets.",
      "Generics matter most in reusable hooks, list components, and typed utility helpers.",
      "Good types improve refactoring confidence and reduce integration mistakes between teams.",
    ],
    interviewAngles: [
      "Explain TypeScript as a design tool, not only as autocomplete.",
      "Show how discriminated unions improve async UI state modeling.",
      "Mention typed reusable hooks and component contracts from your real work.",
    ],
    quickRevision: [
      "Model UI states with unions.",
      "Use narrowing before unsafe access.",
      "Generics help reuse safely.",
      "Types improve refactors and onboarding.",
    ],
    sourceRefs: [
      { title: "TypeScript Handbook Intro", url: "https://www.typescriptlang.org/docs/handbook/intro.html", type: "official-docs" },
      { title: "Narrowing", url: "https://www.typescriptlang.org/docs/handbook/2/narrowing.html", type: "official-docs" },
      { title: "Generics", url: "https://www.typescriptlang.org/docs/handbook/2/generics.html", type: "official-docs" },
    ],
  },
  {
    id: "orp-testing",
    title: "Testing Like a User",
    slug: "testing-like-a-user",
    group: "testing",
    mappedTracks: ["frontend", "react"],
    category: "Testing philosophy and execution",
    summary: "A local pack for React Testing Library and Playwright ideas that make your testing answers feel practical and current.",
    simpleStart: [
      "A good test checks what a real user can see and do.",
      "If a test breaks after a small refactor, it may be testing the wrong thing.",
      "Important flows like login or checkout deserve end-to-end testing.",
    ],
    bestFor: "User-focused test strategy, query priority, resilient selectors, and good end-to-end habits.",
    whyThisMattersForYou:
      "Your resume already mentions Jest and React Testing Library, so this pack helps you turn that into polished interview language instead of tool-only name dropping.",
    keyTakeaways: [
      "Testing Library encourages queries that match how users find elements, especially accessible roles and labels.",
      "Implementation-detail tests are brittle; behavior-focused tests survive refactors better.",
      "Playwright best practices emphasize stable, user-visible assertions and isolated tests.",
      "Testing quality includes loading, error, and accessibility states, not only the happy path.",
    ],
    interviewAngles: [
      "Explain your testing pyramid using risk and confidence, not memorized definitions.",
      "Use accessible queries as proof of user-focused testing.",
      "When discussing E2E, mention resilient selectors and business-critical flows.",
    ],
    quickRevision: [
      "Prefer role and label based queries.",
      "Test behavior over implementation details.",
      "Protect critical flows with E2E.",
      "Include error and loading states.",
    ],
    sourceRefs: [
      { title: "Testing Library Queries", url: "https://testing-library.com/docs/queries/about", type: "official-docs" },
      { title: "Playwright Best Practices", url: "https://playwright.dev/docs/best-practices", type: "official-docs" },
    ],
  },
  {
    id: "orp-performance",
    title: "Performance and Web Vitals",
    slug: "performance-and-web-vitals",
    group: "performance",
    mappedTracks: ["performance-security", "react", "frontend"],
    category: "Performance and Web Vitals",
    summary: "A local digest of high-value web performance ideas that connect directly to React and product interview rounds.",
    simpleStart: [
      "A fast app loads the main content quickly and reacts quickly when people click.",
      "Too much JavaScript can make the browser busy and the screen feel slow.",
      "Good performance means users feel speed, not just good tool scores.",
    ],
    bestFor: "Web vitals, LCP thinking, responsiveness, layout stability, render cost, bundle strategy, and main-thread awareness.",
    whyThisMattersForYou:
      "Performance is one of the strongest themes in your resume, so having crisp language here can become one of your biggest interview strengths.",
    keyTakeaways: [
      "Largest content speed, interaction responsiveness, and layout stability are user-experience metrics, not only Lighthouse scores.",
      "JavaScript cost and main-thread blocking often matter as much as network cost in frontend performance.",
      "Bundle splitting, lazy loading, image strategy, and unnecessary rerender reduction work together rather than independently.",
      "Good performance answers connect metrics to what users feel on real screens.",
    ],
    interviewAngles: [
      "Use this pack when explaining your resume bullets about code splitting and lazy loading.",
      "Frame optimization work as user experience and business impact, not only technical tuning.",
      "Mention measurement before optimization to sound stronger in senior-leaning mid-level rounds.",
    ],
    quickRevision: [
      "Measure before optimizing.",
      "Protect main-thread time.",
      "Reduce bundle and render cost together.",
      "Talk in user-experience terms.",
    ],
    sourceRefs: [
      { title: "web.dev Learn Performance", url: "https://web.dev/learn/performance", type: "official-guide" },
      { title: "web.dev LCP Guide", url: "https://web.dev/articles/lcp", type: "official-guide" },
    ],
  },
  {
    id: "orp-accessibility",
    title: "Accessible Components and Keyboard Support",
    slug: "accessible-components-and-keyboard-support",
    group: "accessibility",
    mappedTracks: ["accessibility", "html-css", "machine-coding"],
    category: "Accessibility and interactive component behavior",
    summary: "A local pack for semantics, keyboard support, and accessible widget behavior that is useful in both theory and machine coding rounds.",
    simpleStart: [
      "Accessible UI means more people can use the app in different ways.",
      "Native HTML elements already know a lot about keyboard and screen-reader behavior.",
      "Custom widgets need clear focus movement, names, and keyboard support.",
    ],
    bestFor: "Semantic HTML, focus behavior, keyboard navigation, accessible names, and ARIA widget expectations.",
    whyThisMattersForYou:
      "Accessibility already appears in your profile, so stronger language here helps you stand out as a thoughtful product engineer instead of only a UI implementer.",
    keyTakeaways: [
      "Semantic HTML gives you built-in accessibility behavior before ARIA is even needed.",
      "Keyboard support, focus visibility, and accessible names are foundational quality checks.",
      "WAI-ARIA patterns matter most when building custom interactive widgets like tabs, dialogs, and comboboxes.",
      "Accessible UI and testability often improve together because both rely on meaningful structure.",
    ],
    interviewAngles: [
      "Use this pack in machine coding when you need to mention keyboard behavior and roles quickly.",
      "Pair accessibility with testing and semantics in your answers.",
      "Avoid saying ARIA solves everything; say semantics first, ARIA where needed.",
    ],
    quickRevision: [
      "Semantics first.",
      "Keyboard and focus always.",
      "Use ARIA only when native HTML is not enough.",
      "Accessible structure improves testing too.",
    ],
    sourceRefs: [
      { title: "web.dev Accessibility", url: "https://web.dev/accessibility", type: "official-guide" },
      { title: "WAI-ARIA Authoring Practices Guide", url: "https://www.w3.org/WAI/ARIA/apg/", type: "official-guide" },
    ],
  },
  {
    id: "orp-system-design",
    title: "Frontend State and Screen Architecture",
    slug: "frontend-state-and-screen-architecture",
    group: "system-design",
    mappedTracks: ["system-design", "react", "frontend"],
    category: "Frontend architecture and screen design",
    summary: "A local architecture pack that turns React learning resources into system-design language for real interview use.",
    simpleStart: [
      "Frontend design means deciding who owns data and how screens talk to each other.",
      "Keep state near the place that truly owns it, then move it up only when needed.",
      "A strong design answer covers loading, errors, performance, and accessibility too.",
    ],
    bestFor: "State ownership, screen decomposition, shared data flow, and explaining how to structure medium-to-large React applications.",
    whyThisMattersForYou:
      "You already have hands-on product experience, so system design rounds are less about syntax and more about showing calm structure and good boundaries.",
    keyTakeaways: [
      "Start architecture answers with user flows and screen responsibilities before discussing tools.",
      "State should live close to ownership and move upward only when multiple consumers truly need it.",
      "Shared UI patterns become easier to scale when component responsibilities are explicit and reusable.",
      "Architecture decisions should cover loading, error states, performance, and accessibility from the start.",
    ],
    interviewAngles: [
      "Use this pack for dashboard, search, table, and workflow-screen system design questions.",
      "Discuss state boundaries and async flow before naming libraries.",
      "Tie component design, performance, and user experience together in one answer.",
    ],
    quickRevision: [
      "Users and screens first.",
      "State follows ownership.",
      "Boundaries beat tool lists.",
      "Include loading, error, performance, and accessibility.",
    ],
    sourceRefs: [
      { title: "Thinking in React", url: "https://react.dev/learn/thinking-in-react", type: "official-docs" },
      { title: "Sharing State Between Components", url: "https://react.dev/learn/sharing-state-between-components", type: "official-docs" },
      { title: "Choosing the State Structure", url: "https://react.dev/learn/choosing-the-state-structure", type: "official-docs" },
    ],
  },
];
